<a href="https://colab.research.google.com/github/ishandahal/stats453-deep_learning_torch/blob/main/perceptron_adaline_linear_regression/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.autograd import grad
import torch.nn.functional as F

In [ ]:
x = torch.tensor([3.])
w = torch.tensor([2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
v = x*w + b
a = F.relu(v)

In [ ]:
a

tensor([7.], grad_fn=<ReluBackward0>)

In [ ]:
grad(a, w, retain_graph=True)

(tensor([3.]),)

In [ ]:
grad(a, b, retain_graph=True)

(tensor([1.]),)

In [ ]:
grad(a, v)

(tensor([1.]),)

Implementing relu function

In [ ]:
x = torch.tensor([3.])
w = torch.tensor([2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

def my_relu(z):
    if z > 0.:
        return z
    else:
        z[:] = 0.
        return z
a = my_relu(x*w + b)
grad(a, w)

(tensor([3.]),)

Eventhough derivative of relu is not defined at 0, PyTorch autograd does not throw an error and does something reasonable

In [ ]:
x = torch.tensor([-1.])
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

def my_relu(z):
    if z > 0.:
        return z
    else:
        z[:] = 0.
        return z
a = my_relu(x*w + b)
grad(a, w, retain_graph=False)

(tensor([-0.]),)